version: '3'

services:
  vote:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      PROXY_API_KEY: '123'
    volumes:
      - ./:/usr/app
      - ./node_modules:/usr/app/node_modules
      - ./.env:/usr/app/.env
